Automated WIP Commit:

diff --git a/bin/command-center b/bin/command-center
--- a/bin/command-center
+++ b/bin/command-center
@@ -1,37 +1,62 @@
 #!/usr/bin/env bash
 
 menu() {
-	local prompt="$1"
-	local options="$2"
-	printf "${options}" | wofi --show dmenu -p "$prompt"
+	printf "$2" | wofi --show dmenu -p "$1"
 }
 
-case "$(menu 'Select Action:' '🖥️Apps \nSystem \n◐ Toggle Light/Dark Mode \n🌑Dark Mode \n☀ Light Mode \n🎨 Themes \n🔤 Fonts\n')" in
-	*Apps*)
-		launcher
-		;;
-	*System*)
-		session-control
-		;;
-	*"Toggle Light/Dark Mode"*)
-		toggle-color-mode
-		;;
-	*"Dark Mode"*)
-		dark-mode
-		;;
-	*"Light Mode"*)
-		light-mode
-		;;
-	*Themes*)
-		select-theme
-		;;
-	*Fonts*)
-		select-font
-		;;
-	*)
-		echo "Invalid action"
-		exit 1
-		;;
-esac
+show_style_menu() {
+	case "$(menu 'Style Menu:' '󰸌  Theme\n  Font\n◐  Toggle Light/Dark Mode \n🌑  Dark Mode \n☀  Light Mode')" in
+		*"Theme"*)
+			select-theme
+			;;
+		*"Font"*)
+			show_font_menu
+			;;
+		*"Toggle"*)
+			toggle-light-dark-mode
+			;;
+		*Dark*)
+			dark-mode
+			;;
+		*Light*)
+			light-mode
+			;;
+		*)
+			echo "Invalid action"
+			exit 1
+			;;
+	esac
+}
+
+show_font_menu() {
+	font-set "$(fonts-list | fuzzy_menu "Select font: ")"
+}
+
+show_theme_menu() {
+	theme-set "$(themes-list | fuzzy_menu "Select theme: ")"
+}
+
+show_menu() {
+	case "$(menu 'Select Action:' '󰀻  Apps \n  Style\n  System')" in
+		*Apps*)
+			launcher
+			;;
+		*System*)
+			session-control
+			;;
+		*Style*)
+			show_style_menu
+			;;
+		*)
+			echo "Invalid action"
+			exit 1
+			;;
+	esac
+}
 
 
+if [[ -n "$1" ]]; then
+	$1
+else
+	show_menu
+fi
